name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build-py-to-exe:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Build with PyInstaller
        run: pyinstaller -F src/main.py --hidden-import sys --add-data src/resources/:./resources/ --name Cave-of-Shadows-AdventureSoft

      - name: Publish
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: dist/Cave-of-Shadows-AdventureSoft.exe
          tag_name: v${{ github.run_number }}
          prerelease: false
          name: v${{ github.run_number }}