name: Build EXE

on:
  push:
    tags:
      - 'v*' # Only run workflow on version tags, e.g. v1.0.0, v1.0.1, v1.0.2, etc.'

jobs:
  build-py-to-exe:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install
      
      - name: Install requirements
        run: uv pip install -r requirements.txt
        env:
          UV_SYSTEM_PYTHON: 1
      
      - name: Build with Pyinstaller
        run: pyinstaller -F src/main.py --add-data src/resources/:./resources/ --name AdventureSoft-Cave-of-Shadows

      - name: Publish
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: dist/AdventureSoft-Cave-of-Shadows.exe
          tag_name: v${{ github.ref_name }}
          prerelease: false
          name: v${{ github.ref_name }}