name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build-py-to-exe:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: 3.13

      - name: Install requirements
        run: uv pip install --system -r requirements.txt

      - name: Build with PyInstaller
        run: uv run pyinstaller -F src/main.py --hidden-import sys --add-data src/resources/:./resources/ --name Cave-of-Shadows-AdventureSoft

      - name: Publish
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: dist/Cave-of-Shadows-AdventureSoft.exe
          tag_name: v${{ github.run_number }}
          prerelease: false
          name: v${{ github.run_number }}